/* AUTO-GENERATED by scripts/generate-uianchor.mjs — do not edit */
/* eslint-disable */
export type UIAnchorId =
  | "administrative.dashboard"
  | "administrative.logout"
  | "administrative.nav.appointments"
  | "administrative.nav.dept-info"
  | "administrative.nav.overview"
  | "administrative.nav.patients"
  | "administrative.nav.queue"
  | "administrative.nav.subdepts"
  | "auth.change-password.confirm"
  | "auth.change-password.current"
  | "auth.change-password.new"
  | "auth.change-password.submit"
  | "auth.finance.login.email"
  | "auth.finance.login.password"
  | "auth.finance.login.submit"
  | "auth.forgot.close"
  | "auth.forgot.confirm"
  | "auth.forgot.email"
  | "auth.forgot.go-to-signin"
  | "auth.forgot.otp-1"
  | "auth.forgot.otp-2"
  | "auth.forgot.otp-3"
  | "auth.forgot.otp-4"
  | "auth.forgot.otp-5"
  | "auth.forgot.otp-6"
  | "auth.forgot.password"
  | "auth.forgot.resend-otp"
  | "auth.forgot.send-otp"
  | "auth.forgot.submit"
  | "auth.forgot.verify-otp"
  | "auth.login.email"
  | "auth.login.password"
  | "auth.login.submit"
  | "auth.parentdept.login.email"
  | "auth.parentdept.login.password"
  | "auth.parentdept.login.submit"
  | "auth.signup.admin-name"
  | "auth.signup.back"
  | "auth.signup.confirm-password"
  | "auth.signup.email"
  | "auth.signup.hospital-name"
  | "auth.signup.mobile"
  | "auth.signup.otp-1"
  | "auth.signup.otp-2"
  | "auth.signup.otp-3"
  | "auth.signup.otp-4"
  | "auth.signup.otp-5"
  | "auth.signup.otp-6"
  | "auth.signup.password"
  | "auth.signup.resend-otp"
  | "auth.signup.submit"
  | "auth.signup.verify"
  | "auth.staff.login.email"
  | "auth.staff.login.password"
  | "auth.staff.login.submit"
  | "auth.subdept.login.email"
  | "auth.subdept.login.password"
  | "auth.subdept.login.submit"
  | "auth.superadmin.login.email"
  | "auth.superadmin.login.password"
  | "auth.superadmin.login.security-key"
  | "auth.superadmin.login.submit"
  | "clinical.dashboard"
  | "clinical.dashboard.loading"
  | "clinical.logout"
  | "clinical.nav.appointments"
  | "clinical.nav.dept-info"
  | "clinical.nav.overview"
  | "clinical.nav.patients"
  | "clinical.nav.queue"
  | "clinical.nav.subdepts"
  | "diagnostic.dashboard"
  | "diagnostic.logout"
  | "diagnostic.nav.appointments"
  | "diagnostic.nav.dept-info"
  | "diagnostic.nav.overview"
  | "diagnostic.nav.patients"
  | "diagnostic.nav.queue"
  | "diagnostic.nav.subdepts"
  | "doctor.attendance.checkout"
  | "doctor.dashboard"
  | "doctor.dashboard.loading"
  | "doctor.inventory.create"
  | "doctor.inventory.search"
  | "doctor.ipd.admit"
  | "doctor.ipd.search"
  | "doctor.logout"
  | "doctor.nav.appointments"
  | "doctor.nav.attendance"
  | "doctor.nav.patients"
  | "doctor.nav.prescription-settings"
  | "doctor.nav.profile"
  | "doctor.nav.reports"
  | "doctor.nav.rx"
  | "doctor.nav.schedule"
  | "doctor.nav.schedule-mgmt"
  | "doctor.nav.treatment-plans"
  | "doctor.patients.create"
  | "doctor.patients.search"
  | "doctor.profile.save"
  | "doctor.rx.add-medication"
  | "doctor.rx.save"
  | "doctor.rx.voice.close"
  | "doctor.rx.voice.start"
  | "doctor.schedule.consult"
  | "doctor.schedule.edit-rx"
  | "doctor.schedule.view-rx"
  | "finance.bills.create"
  | "finance.bills.create-alt"
  | "finance.bills.create-list"
  | "finance.bills.submit"
  | "finance.dashboard"
  | "finance.dashboard.loading"
  | "finance.expenses.create"
  | "finance.expenses.create-list"
  | "finance.expenses.submit"
  | "finance.logout"
  | "finance.nav.bills"
  | "finance.nav.expenses"
  | "finance.nav.overview"
  | "finance.nav.payments"
  | "finance.nav.reports"
  | "finance.payments.initiate"
  | "finance.payments.initiate-modal"
  | "finance.payments.submit"
  | "hospitaladmin.appointments"
  | "hospitaladmin.billing"
  | "hospitaladmin.configure"
  | "hospitaladmin.configure.departments.create"
  | "hospitaladmin.configure.departments.save"
  | "hospitaladmin.configure.departments.search"
  | "hospitaladmin.configure.loading"
  | "hospitaladmin.configure.services.create"
  | "hospitaladmin.configure.services.save"
  | "hospitaladmin.configure.subdepartments.create"
  | "hospitaladmin.configure.subdepartments.save"
  | "hospitaladmin.configure.subdepartments.search"
  | "hospitaladmin.configure.tab.appointments"
  | "hospitaladmin.configure.tab.billing"
  | "hospitaladmin.configure.tab.departments"
  | "hospitaladmin.configure.tab.doctors"
  | "hospitaladmin.configure.tab.finance"
  | "hospitaladmin.configure.tab.inventory"
  | "hospitaladmin.configure.tab.overview"
  | "hospitaladmin.configure.tab.patients"
  | "hospitaladmin.configure.tab.permissions"
  | "hospitaladmin.configure.tab.services"
  | "hospitaladmin.configure.tab.settings"
  | "hospitaladmin.configure.tab.staff"
  | "hospitaladmin.configure.tab.subdepts"
  | "hospitaladmin.configure.tab.treatments"
  | "hospitaladmin.configure.tab.wards"
  | "hospitaladmin.configure.wards.create"
  | "hospitaladmin.configure.wards.save"
  | "hospitaladmin.consultation"
  | "hospitaladmin.consultation.start"
  | "hospitaladmin.consultation.status"
  | "hospitaladmin.dashboard"
  | "hospitaladmin.dashboard.loading"
  | "hospitaladmin.dashboard.tab.appointments"
  | "hospitaladmin.dashboard.tab.billing"
  | "hospitaladmin.dashboard.tab.departments"
  | "hospitaladmin.dashboard.tab.inventory"
  | "hospitaladmin.dashboard.tab.ipd"
  | "hospitaladmin.dashboard.tab.overview"
  | "hospitaladmin.dashboard.tab.patients"
  | "hospitaladmin.dashboard.tab.reports"
  | "hospitaladmin.dashboard.tab.staff"
  | "hospitaladmin.doctors"
  | "hospitaladmin.doctors.create"
  | "hospitaladmin.doctors.loading"
  | "hospitaladmin.doctors.save"
  | "hospitaladmin.doctors.search"
  | "hospitaladmin.finance"
  | "hospitaladmin.finance.expense.submit"
  | "hospitaladmin.finance.loading"
  | "hospitaladmin.finance.revenue.submit"
  | "hospitaladmin.inventory.create"
  | "hospitaladmin.inventory.search"
  | "hospitaladmin.ipd.admit"
  | "hospitaladmin.ipd.search"
  | "hospitaladmin.logout"
  | "hospitaladmin.nav.appointments"
  | "hospitaladmin.nav.billing"
  | "hospitaladmin.nav.configure"
  | "hospitaladmin.nav.consultation"
  | "hospitaladmin.nav.departments"
  | "hospitaladmin.nav.doctors"
  | "hospitaladmin.nav.finance"
  | "hospitaladmin.nav.inventory"
  | "hospitaladmin.nav.ipd"
  | "hospitaladmin.nav.overview"
  | "hospitaladmin.nav.patients"
  | "hospitaladmin.nav.reports"
  | "hospitaladmin.nav.staff"
  | "hospitaladmin.patients.create"
  | "hospitaladmin.patients.search"
  | "hospitaladmin.profile"
  | "hospitaladmin.profile.change-password.submit"
  | "hospitaladmin.profile.confirm-password"
  | "hospitaladmin.profile.current-password"
  | "hospitaladmin.profile.email"
  | "hospitaladmin.profile.loading"
  | "hospitaladmin.profile.name"
  | "hospitaladmin.profile.new-password"
  | "hospitaladmin.profile.save"
  | "hospitaladmin.staff"
  | "hospitaladmin.staff.create"
  | "hospitaladmin.staff.loading"
  | "hospitaladmin.staff.save"
  | "hospitaladmin.staff.search"
  | "parentdept.dashboard"
  | "parentdept.dashboard.loading"
  | "parentdept.dashboard.tab.completed"
  | "parentdept.dashboard.tab.overview"
  | "parentdept.dashboard.tab.procedures"
  | "parentdept.dashboard.tab.queue"
  | "parentdept.dashboard.tab.records"
  | "parentdept.inventory.create"
  | "parentdept.inventory.search"
  | "parentdept.ipd.admit"
  | "parentdept.ipd.search"
  | "parentdept.logout"
  | "parentdept.nav.analytics"
  | "parentdept.nav.billing"
  | "parentdept.nav.inventory"
  | "parentdept.nav.overview"
  | "parentdept.nav.purchases"
  | "parentdept.nav.queue"
  | "parentdept.nav.reports"
  | "parentdept.nav.subdepts"
  | "parentdept.patients.create"
  | "parentdept.patients.search"
  | "public.booking.date"
  | "public.booking.department"
  | "public.booking.doctor"
  | "public.booking.email"
  | "public.booking.name"
  | "public.booking.phone"
  | "public.booking.submit"
  | "public.brand.wordmark"
  | "public.landing.cta-book-demo"
  | "public.landing.cta-signup"
  | "public.nav.book"
  | "public.nav.login"
  | "receptionist.appointments.create"
  | "receptionist.dashboard"
  | "receptionist.dashboard.loading"
  | "receptionist.logout"
  | "receptionist.nav.book"
  | "receptionist.nav.patients"
  | "receptionist.nav.queue"
  | "shared.patients.search"
  | "staff.dashboard"
  | "staff.dashboard.loading"
  | "staff.inventory.create"
  | "staff.inventory.search"
  | "staff.ipd.admit"
  | "staff.ipd.search"
  | "staff.logout"
  | "staff.nav.appointments"
  | "staff.nav.billing"
  | "staff.nav.bills"
  | "staff.nav.followups"
  | "staff.nav.overview"
  | "staff.nav.patients"
  | "staff.nav.queue"
  | "staff.patients.create"
  | "staff.patients.search"
  | "subdept.billing-dept.billing-queue"
  | "subdept.billing-dept.inventory.create"
  | "subdept.billing-dept.inventory.search"
  | "subdept.billing-dept.ipd.admit"
  | "subdept.billing-dept.ipd.search"
  | "subdept.billing-dept.open-queue"
  | "subdept.billing-dept.patients.create"
  | "subdept.billing-dept.patients.search"
  | "subdept.billing-dept.view-finance"
  | "subdept.critical-care.admit"
  | "subdept.critical-care.discharge"
  | "subdept.critical-care.refresh"
  | "subdept.dashboard"
  | "subdept.dashboard.loading"
  | "subdept.hr.manage-doctors"
  | "subdept.hr.manage-staff"
  | "subdept.hr.manage-staff-doctors"
  | "subdept.hr.open-doctors"
  | "subdept.hr.open-staff"
  | "subdept.hr.refresh-stats"
  | "subdept.modal.edit-record.cancel"
  | "subdept.modal.edit-record.submit"
  | "subdept.modal.transfer-patient.cancel"
  | "subdept.modal.transfer-patient.submit"
  | "subdept.modal.view-prescription.download"
  | "subdept.pathology.inventory.create"
  | "subdept.pathology.inventory.search"
  | "subdept.pathology.ipd.admit"
  | "subdept.pathology.ipd.search"
  | "subdept.pathology.patients.create"
  | "subdept.pathology.patients.search"
  | "subdept.patients.inventory.create"
  | "subdept.patients.inventory.search"
  | "subdept.patients.ipd.admit"
  | "subdept.patients.ipd.search"
  | "subdept.patients.patients.create"
  | "subdept.patients.patients.search"
  | "subdept.pharmacy.inventory.create"
  | "subdept.pharmacy.inventory.search"
  | "subdept.pharmacy.ipd.admit"
  | "subdept.pharmacy.ipd.search"
  | "subdept.pharmacy.patients.create"
  | "subdept.pharmacy.patients.search"
  | "subdept.shell.logout"
  | "subdept.shell.nav.account-settings"
  | "subdept.shell.nav.analytics"
  | "subdept.shell.nav.appointments"
  | "subdept.shell.nav.billing"
  | "subdept.shell.nav.billing-queue"
  | "subdept.shell.nav.consultations"
  | "subdept.shell.nav.counter-sell"
  | "subdept.shell.nav.doctors"
  | "subdept.shell.nav.expense"
  | "subdept.shell.nav.expenses"
  | "subdept.shell.nav.finance"
  | "subdept.shell.nav.inventory"
  | "subdept.shell.nav.orders"
  | "subdept.shell.nav.overview"
  | "subdept.shell.nav.panels"
  | "subdept.shell.nav.patients"
  | "subdept.shell.nav.procedures"
  | "subdept.shell.nav.purchases"
  | "subdept.shell.nav.queue"
  | "subdept.shell.nav.records"
  | "subdept.shell.nav.reports"
  | "subdept.shell.nav.results"
  | "subdept.shell.nav.revenue"
  | "subdept.shell.nav.samples"
  | "subdept.shell.nav.staff"
  | "subdept.shell.nav.tests"
  | "subdept.specialty.complete"
  | "subdept.specialty.refresh"
  | "subdept.specialty.refresh-records"
  | "subdept.specialty.start"
  | "superadmin.dashboard"
  | "superadmin.dashboard.loading"
  | "superadmin.hospitals.create.submit"
  | "superadmin.logout"
  | "superadmin.nav.activity"
  | "superadmin.nav.hospitals"
  | "superadmin.nav.overview"
  | "superadmin.nav.settings"
  | "support.dashboard"
  | "support.logout"
  | "support.nav.appointments"
  | "support.nav.dept-info"
  | "support.nav.overview"
  | "support.nav.patients"
  | "support.nav.queue"
  | "support.nav.subdepts";

export const UI_ANCHOR_IDS = [
  "administrative.dashboard",
  "administrative.logout",
  "administrative.nav.appointments",
  "administrative.nav.dept-info",
  "administrative.nav.overview",
  "administrative.nav.patients",
  "administrative.nav.queue",
  "administrative.nav.subdepts",
  "auth.change-password.confirm",
  "auth.change-password.current",
  "auth.change-password.new",
  "auth.change-password.submit",
  "auth.finance.login.email",
  "auth.finance.login.password",
  "auth.finance.login.submit",
  "auth.forgot.close",
  "auth.forgot.confirm",
  "auth.forgot.email",
  "auth.forgot.go-to-signin",
  "auth.forgot.otp-1",
  "auth.forgot.otp-2",
  "auth.forgot.otp-3",
  "auth.forgot.otp-4",
  "auth.forgot.otp-5",
  "auth.forgot.otp-6",
  "auth.forgot.password",
  "auth.forgot.resend-otp",
  "auth.forgot.send-otp",
  "auth.forgot.submit",
  "auth.forgot.verify-otp",
  "auth.login.email",
  "auth.login.password",
  "auth.login.submit",
  "auth.parentdept.login.email",
  "auth.parentdept.login.password",
  "auth.parentdept.login.submit",
  "auth.signup.admin-name",
  "auth.signup.back",
  "auth.signup.confirm-password",
  "auth.signup.email",
  "auth.signup.hospital-name",
  "auth.signup.mobile",
  "auth.signup.otp-1",
  "auth.signup.otp-2",
  "auth.signup.otp-3",
  "auth.signup.otp-4",
  "auth.signup.otp-5",
  "auth.signup.otp-6",
  "auth.signup.password",
  "auth.signup.resend-otp",
  "auth.signup.submit",
  "auth.signup.verify",
  "auth.staff.login.email",
  "auth.staff.login.password",
  "auth.staff.login.submit",
  "auth.subdept.login.email",
  "auth.subdept.login.password",
  "auth.subdept.login.submit",
  "auth.superadmin.login.email",
  "auth.superadmin.login.password",
  "auth.superadmin.login.security-key",
  "auth.superadmin.login.submit",
  "clinical.dashboard",
  "clinical.dashboard.loading",
  "clinical.logout",
  "clinical.nav.appointments",
  "clinical.nav.dept-info",
  "clinical.nav.overview",
  "clinical.nav.patients",
  "clinical.nav.queue",
  "clinical.nav.subdepts",
  "diagnostic.dashboard",
  "diagnostic.logout",
  "diagnostic.nav.appointments",
  "diagnostic.nav.dept-info",
  "diagnostic.nav.overview",
  "diagnostic.nav.patients",
  "diagnostic.nav.queue",
  "diagnostic.nav.subdepts",
  "doctor.attendance.checkout",
  "doctor.dashboard",
  "doctor.dashboard.loading",
  "doctor.inventory.create",
  "doctor.inventory.search",
  "doctor.ipd.admit",
  "doctor.ipd.search",
  "doctor.logout",
  "doctor.nav.appointments",
  "doctor.nav.attendance",
  "doctor.nav.patients",
  "doctor.nav.prescription-settings",
  "doctor.nav.profile",
  "doctor.nav.reports",
  "doctor.nav.rx",
  "doctor.nav.schedule",
  "doctor.nav.schedule-mgmt",
  "doctor.nav.treatment-plans",
  "doctor.patients.create",
  "doctor.patients.search",
  "doctor.profile.save",
  "doctor.rx.add-medication",
  "doctor.rx.save",
  "doctor.rx.voice.close",
  "doctor.rx.voice.start",
  "doctor.schedule.consult",
  "doctor.schedule.edit-rx",
  "doctor.schedule.view-rx",
  "finance.bills.create",
  "finance.bills.create-alt",
  "finance.bills.create-list",
  "finance.bills.submit",
  "finance.dashboard",
  "finance.dashboard.loading",
  "finance.expenses.create",
  "finance.expenses.create-list",
  "finance.expenses.submit",
  "finance.logout",
  "finance.nav.bills",
  "finance.nav.expenses",
  "finance.nav.overview",
  "finance.nav.payments",
  "finance.nav.reports",
  "finance.payments.initiate",
  "finance.payments.initiate-modal",
  "finance.payments.submit",
  "hospitaladmin.appointments",
  "hospitaladmin.billing",
  "hospitaladmin.configure",
  "hospitaladmin.configure.departments.create",
  "hospitaladmin.configure.departments.save",
  "hospitaladmin.configure.departments.search",
  "hospitaladmin.configure.loading",
  "hospitaladmin.configure.services.create",
  "hospitaladmin.configure.services.save",
  "hospitaladmin.configure.subdepartments.create",
  "hospitaladmin.configure.subdepartments.save",
  "hospitaladmin.configure.subdepartments.search",
  "hospitaladmin.configure.tab.appointments",
  "hospitaladmin.configure.tab.billing",
  "hospitaladmin.configure.tab.departments",
  "hospitaladmin.configure.tab.doctors",
  "hospitaladmin.configure.tab.finance",
  "hospitaladmin.configure.tab.inventory",
  "hospitaladmin.configure.tab.overview",
  "hospitaladmin.configure.tab.patients",
  "hospitaladmin.configure.tab.permissions",
  "hospitaladmin.configure.tab.services",
  "hospitaladmin.configure.tab.settings",
  "hospitaladmin.configure.tab.staff",
  "hospitaladmin.configure.tab.subdepts",
  "hospitaladmin.configure.tab.treatments",
  "hospitaladmin.configure.tab.wards",
  "hospitaladmin.configure.wards.create",
  "hospitaladmin.configure.wards.save",
  "hospitaladmin.consultation",
  "hospitaladmin.consultation.start",
  "hospitaladmin.consultation.status",
  "hospitaladmin.dashboard",
  "hospitaladmin.dashboard.loading",
  "hospitaladmin.dashboard.tab.appointments",
  "hospitaladmin.dashboard.tab.billing",
  "hospitaladmin.dashboard.tab.departments",
  "hospitaladmin.dashboard.tab.inventory",
  "hospitaladmin.dashboard.tab.ipd",
  "hospitaladmin.dashboard.tab.overview",
  "hospitaladmin.dashboard.tab.patients",
  "hospitaladmin.dashboard.tab.reports",
  "hospitaladmin.dashboard.tab.staff",
  "hospitaladmin.doctors",
  "hospitaladmin.doctors.create",
  "hospitaladmin.doctors.loading",
  "hospitaladmin.doctors.save",
  "hospitaladmin.doctors.search",
  "hospitaladmin.finance",
  "hospitaladmin.finance.expense.submit",
  "hospitaladmin.finance.loading",
  "hospitaladmin.finance.revenue.submit",
  "hospitaladmin.inventory.create",
  "hospitaladmin.inventory.search",
  "hospitaladmin.ipd.admit",
  "hospitaladmin.ipd.search",
  "hospitaladmin.logout",
  "hospitaladmin.nav.appointments",
  "hospitaladmin.nav.billing",
  "hospitaladmin.nav.configure",
  "hospitaladmin.nav.consultation",
  "hospitaladmin.nav.departments",
  "hospitaladmin.nav.doctors",
  "hospitaladmin.nav.finance",
  "hospitaladmin.nav.inventory",
  "hospitaladmin.nav.ipd",
  "hospitaladmin.nav.overview",
  "hospitaladmin.nav.patients",
  "hospitaladmin.nav.reports",
  "hospitaladmin.nav.staff",
  "hospitaladmin.patients.create",
  "hospitaladmin.patients.search",
  "hospitaladmin.profile",
  "hospitaladmin.profile.change-password.submit",
  "hospitaladmin.profile.confirm-password",
  "hospitaladmin.profile.current-password",
  "hospitaladmin.profile.email",
  "hospitaladmin.profile.loading",
  "hospitaladmin.profile.name",
  "hospitaladmin.profile.new-password",
  "hospitaladmin.profile.save",
  "hospitaladmin.staff",
  "hospitaladmin.staff.create",
  "hospitaladmin.staff.loading",
  "hospitaladmin.staff.save",
  "hospitaladmin.staff.search",
  "parentdept.dashboard",
  "parentdept.dashboard.loading",
  "parentdept.dashboard.tab.completed",
  "parentdept.dashboard.tab.overview",
  "parentdept.dashboard.tab.procedures",
  "parentdept.dashboard.tab.queue",
  "parentdept.dashboard.tab.records",
  "parentdept.inventory.create",
  "parentdept.inventory.search",
  "parentdept.ipd.admit",
  "parentdept.ipd.search",
  "parentdept.logout",
  "parentdept.nav.analytics",
  "parentdept.nav.billing",
  "parentdept.nav.inventory",
  "parentdept.nav.overview",
  "parentdept.nav.purchases",
  "parentdept.nav.queue",
  "parentdept.nav.reports",
  "parentdept.nav.subdepts",
  "parentdept.patients.create",
  "parentdept.patients.search",
  "public.booking.date",
  "public.booking.department",
  "public.booking.doctor",
  "public.booking.email",
  "public.booking.name",
  "public.booking.phone",
  "public.booking.submit",
  "public.brand.wordmark",
  "public.landing.cta-book-demo",
  "public.landing.cta-signup",
  "public.nav.book",
  "public.nav.login",
  "receptionist.appointments.create",
  "receptionist.dashboard",
  "receptionist.dashboard.loading",
  "receptionist.logout",
  "receptionist.nav.book",
  "receptionist.nav.patients",
  "receptionist.nav.queue",
  "shared.patients.search",
  "staff.dashboard",
  "staff.dashboard.loading",
  "staff.inventory.create",
  "staff.inventory.search",
  "staff.ipd.admit",
  "staff.ipd.search",
  "staff.logout",
  "staff.nav.appointments",
  "staff.nav.billing",
  "staff.nav.bills",
  "staff.nav.followups",
  "staff.nav.overview",
  "staff.nav.patients",
  "staff.nav.queue",
  "staff.patients.create",
  "staff.patients.search",
  "subdept.billing-dept.billing-queue",
  "subdept.billing-dept.inventory.create",
  "subdept.billing-dept.inventory.search",
  "subdept.billing-dept.ipd.admit",
  "subdept.billing-dept.ipd.search",
  "subdept.billing-dept.open-queue",
  "subdept.billing-dept.patients.create",
  "subdept.billing-dept.patients.search",
  "subdept.billing-dept.view-finance",
  "subdept.critical-care.admit",
  "subdept.critical-care.discharge",
  "subdept.critical-care.refresh",
  "subdept.dashboard",
  "subdept.dashboard.loading",
  "subdept.hr.manage-doctors",
  "subdept.hr.manage-staff",
  "subdept.hr.manage-staff-doctors",
  "subdept.hr.open-doctors",
  "subdept.hr.open-staff",
  "subdept.hr.refresh-stats",
  "subdept.modal.edit-record.cancel",
  "subdept.modal.edit-record.submit",
  "subdept.modal.transfer-patient.cancel",
  "subdept.modal.transfer-patient.submit",
  "subdept.modal.view-prescription.download",
  "subdept.pathology.inventory.create",
  "subdept.pathology.inventory.search",
  "subdept.pathology.ipd.admit",
  "subdept.pathology.ipd.search",
  "subdept.pathology.patients.create",
  "subdept.pathology.patients.search",
  "subdept.patients.inventory.create",
  "subdept.patients.inventory.search",
  "subdept.patients.ipd.admit",
  "subdept.patients.ipd.search",
  "subdept.patients.patients.create",
  "subdept.patients.patients.search",
  "subdept.pharmacy.inventory.create",
  "subdept.pharmacy.inventory.search",
  "subdept.pharmacy.ipd.admit",
  "subdept.pharmacy.ipd.search",
  "subdept.pharmacy.patients.create",
  "subdept.pharmacy.patients.search",
  "subdept.shell.logout",
  "subdept.shell.nav.account-settings",
  "subdept.shell.nav.analytics",
  "subdept.shell.nav.appointments",
  "subdept.shell.nav.billing",
  "subdept.shell.nav.billing-queue",
  "subdept.shell.nav.consultations",
  "subdept.shell.nav.counter-sell",
  "subdept.shell.nav.doctors",
  "subdept.shell.nav.expense",
  "subdept.shell.nav.expenses",
  "subdept.shell.nav.finance",
  "subdept.shell.nav.inventory",
  "subdept.shell.nav.orders",
  "subdept.shell.nav.overview",
  "subdept.shell.nav.panels",
  "subdept.shell.nav.patients",
  "subdept.shell.nav.procedures",
  "subdept.shell.nav.purchases",
  "subdept.shell.nav.queue",
  "subdept.shell.nav.records",
  "subdept.shell.nav.reports",
  "subdept.shell.nav.results",
  "subdept.shell.nav.revenue",
  "subdept.shell.nav.samples",
  "subdept.shell.nav.staff",
  "subdept.shell.nav.tests",
  "subdept.specialty.complete",
  "subdept.specialty.refresh",
  "subdept.specialty.refresh-records",
  "subdept.specialty.start",
  "superadmin.dashboard",
  "superadmin.dashboard.loading",
  "superadmin.hospitals.create.submit",
  "superadmin.logout",
  "superadmin.nav.activity",
  "superadmin.nav.hospitals",
  "superadmin.nav.overview",
  "superadmin.nav.settings",
  "support.dashboard",
  "support.logout",
  "support.nav.appointments",
  "support.nav.dept-info",
  "support.nav.overview",
  "support.nav.patients",
  "support.nav.queue",
  "support.nav.subdepts",
] as const satisfies readonly UIAnchorId[];
