/* AUTO-GENERATED by scripts/generate-uianchor.mjs — do not edit */
/* eslint-disable */
export type UIAnchorId =
  | "administrative.dashboard"
  | "administrative.logout"
  | "administrative.nav.appointments"
  | "administrative.nav.dept-info"
  | "administrative.nav.overview"
  | "administrative.nav.patients"
  | "administrative.nav.queue"
  | "administrative.nav.subdepts"
  | "auth.change-password.confirm"
  | "auth.change-password.current"
  | "auth.change-password.new"
  | "auth.change-password.submit"
  | "auth.finance.login.email"
  | "auth.finance.login.password"
  | "auth.finance.login.submit"
  | "auth.forgot.close"
  | "auth.forgot.confirm"
  | "auth.forgot.email"
  | "auth.forgot.go-to-signin"
  | "auth.forgot.otp-1"
  | "auth.forgot.otp-2"
  | "auth.forgot.otp-3"
  | "auth.forgot.otp-4"
  | "auth.forgot.otp-5"
  | "auth.forgot.otp-6"
  | "auth.forgot.password"
  | "auth.forgot.resend-otp"
  | "auth.forgot.send-otp"
  | "auth.forgot.submit"
  | "auth.forgot.verify-otp"
  | "auth.login.email"
  | "auth.login.password"
  | "auth.login.submit"
  | "auth.parentdept.login.email"
  | "auth.parentdept.login.password"
  | "auth.parentdept.login.submit"
  | "auth.signup.admin-name"
  | "auth.signup.back"
  | "auth.signup.confirm-password"
  | "auth.signup.email"
  | "auth.signup.hospital-name"
  | "auth.signup.mobile"
  | "auth.signup.otp-1"
  | "auth.signup.otp-2"
  | "auth.signup.otp-3"
  | "auth.signup.otp-4"
  | "auth.signup.otp-5"
  | "auth.signup.otp-6"
  | "auth.signup.password"
  | "auth.signup.resend-otp"
  | "auth.signup.submit"
  | "auth.signup.verify"
  | "auth.staff.login.email"
  | "auth.staff.login.password"
  | "auth.staff.login.submit"
  | "auth.subdept.login.email"
  | "auth.subdept.login.password"
  | "auth.subdept.login.submit"
  | "auth.superadmin.login.email"
  | "auth.superadmin.login.password"
  | "auth.superadmin.login.security-key"
  | "auth.superadmin.login.submit"
  | "clinical.dashboard"
  | "clinical.dashboard.loading"
  | "clinical.dental.dashboard"
  | "clinical.followup.dashboard"
  | "clinical.logout"
  | "clinical.nav.appointments"
  | "clinical.nav.dept-info"
  | "clinical.nav.overview"
  | "clinical.nav.patients"
  | "clinical.nav.queue"
  | "clinical.nav.subdepts"
  | "clinical.nursing.dashboard"
  | "clinical.opd.dashboard"
  | "diagnostic.dashboard"
  | "diagnostic.lab.dashboard"
  | "diagnostic.logout"
  | "diagnostic.nav.appointments"
  | "diagnostic.nav.dept-info"
  | "diagnostic.nav.overview"
  | "diagnostic.nav.patients"
  | "diagnostic.nav.queue"
  | "diagnostic.nav.subdepts"
  | "doctor.appointments.booking.confirm"
  | "doctor.appointments.booking.date"
  | "doctor.appointments.booking.doctor"
  | "doctor.appointments.booking.patient-result"
  | "doctor.appointments.booking.patient-search"
  | "doctor.appointments.booking.slot"
  | "doctor.appointments.create"
  | "doctor.appointments.search"
  | "doctor.attendance.checkout"
  | "doctor.availability.modal"
  | "doctor.dashboard"
  | "doctor.dashboard.loading"
  | "doctor.inventory.create"
  | "doctor.inventory.search"
  | "doctor.ipd.admit"
  | "doctor.ipd.search"
  | "doctor.logout"
  | "doctor.nav.appointments"
  | "doctor.nav.attendance"
  | "doctor.nav.patients"
  | "doctor.nav.prescription-settings"
  | "doctor.nav.profile"
  | "doctor.nav.reports"
  | "doctor.nav.rx"
  | "doctor.nav.schedule"
  | "doctor.nav.schedule-mgmt"
  | "doctor.nav.treatment-plans"
  | "doctor.patient-profile.panel"
  | "doctor.patients.appointment.complete"
  | "doctor.patients.create"
  | "doctor.patients.form.gender"
  | "doctor.patients.form.name"
  | "doctor.patients.form.phone"
  | "doctor.patients.form.submit"
  | "doctor.patients.search"
  | "doctor.patients.view"
  | "doctor.prescription-settings.panel"
  | "doctor.profile"
  | "doctor.profile.panel"
  | "doctor.profile.save"
  | "doctor.rx.add-medication"
  | "doctor.rx.management-panel"
  | "doctor.rx.prescription-page"
  | "doctor.rx.save"
  | "doctor.rx.voice.close"
  | "doctor.rx.voice.recorder"
  | "doctor.rx.voice.start"
  | "doctor.schedule.consult"
  | "doctor.schedule.edit-rx"
  | "doctor.schedule.full-week"
  | "doctor.schedule.modal"
  | "doctor.schedule.save"
  | "doctor.schedule.view-rx"
  | "doctor.treatment-plan.panel"
  | "finance.bills.create"
  | "finance.bills.create-alt"
  | "finance.bills.create-list"
  | "finance.bills.submit"
  | "finance.dashboard"
  | "finance.dashboard.loading"
  | "finance.dept.panel"
  | "finance.expenses.create"
  | "finance.expenses.create-list"
  | "finance.expenses.submit"
  | "finance.logout"
  | "finance.nav.bills"
  | "finance.nav.expenses"
  | "finance.nav.overview"
  | "finance.nav.payments"
  | "finance.nav.reports"
  | "finance.payments.initiate"
  | "finance.payments.initiate-modal"
  | "finance.payments.submit"
  | "hospitaladmin.appointments"
  | "hospitaladmin.appointments.booking.confirm"
  | "hospitaladmin.appointments.booking.date"
  | "hospitaladmin.appointments.booking.doctor"
  | "hospitaladmin.appointments.booking.patient-result"
  | "hospitaladmin.appointments.booking.patient-search"
  | "hospitaladmin.appointments.booking.slot"
  | "hospitaladmin.appointments.create"
  | "hospitaladmin.appointments.modal"
  | "hospitaladmin.appointments.search"
  | "hospitaladmin.billing"
  | "hospitaladmin.configure"
  | "hospitaladmin.configure.departments.create"
  | "hospitaladmin.configure.departments.panel"
  | "hospitaladmin.configure.departments.save"
  | "hospitaladmin.configure.departments.search"
  | "hospitaladmin.configure.loading"
  | "hospitaladmin.configure.services.create"
  | "hospitaladmin.configure.services.save"
  | "hospitaladmin.configure.subdepartments.create"
  | "hospitaladmin.configure.subdepartments.save"
  | "hospitaladmin.configure.subdepartments.search"
  | "hospitaladmin.configure.tab.appointments"
  | "hospitaladmin.configure.tab.billing"
  | "hospitaladmin.configure.tab.departments"
  | "hospitaladmin.configure.tab.doctors"
  | "hospitaladmin.configure.tab.finance"
  | "hospitaladmin.configure.tab.inventory"
  | "hospitaladmin.configure.tab.overview"
  | "hospitaladmin.configure.tab.patients"
  | "hospitaladmin.configure.tab.permissions"
  | "hospitaladmin.configure.tab.services"
  | "hospitaladmin.configure.tab.settings"
  | "hospitaladmin.configure.tab.staff"
  | "hospitaladmin.configure.tab.subdepts"
  | "hospitaladmin.configure.tab.treatments"
  | "hospitaladmin.configure.tab.wards"
  | "hospitaladmin.configure.wards.create"
  | "hospitaladmin.configure.wards.save"
  | "hospitaladmin.consultation"
  | "hospitaladmin.consultation.prescription-page"
  | "hospitaladmin.consultation.start"
  | "hospitaladmin.consultation.status"
  | "hospitaladmin.dashboard"
  | "hospitaladmin.dashboard.loading"
  | "hospitaladmin.dashboard.tab.appointments"
  | "hospitaladmin.dashboard.tab.billing"
  | "hospitaladmin.dashboard.tab.departments"
  | "hospitaladmin.dashboard.tab.inventory"
  | "hospitaladmin.dashboard.tab.ipd"
  | "hospitaladmin.dashboard.tab.overview"
  | "hospitaladmin.dashboard.tab.patients"
  | "hospitaladmin.dashboard.tab.reports"
  | "hospitaladmin.dashboard.tab.staff"
  | "hospitaladmin.doctors"
  | "hospitaladmin.doctors.create"
  | "hospitaladmin.doctors.form.consultation-fee"
  | "hospitaladmin.doctors.form.email"
  | "hospitaladmin.doctors.form.name"
  | "hospitaladmin.doctors.form.phone"
  | "hospitaladmin.doctors.form.specialization"
  | "hospitaladmin.doctors.loading"
  | "hospitaladmin.doctors.save"
  | "hospitaladmin.doctors.schedule"
  | "hospitaladmin.doctors.schedule.appointments.booking.confirm"
  | "hospitaladmin.doctors.schedule.appointments.booking.date"
  | "hospitaladmin.doctors.schedule.appointments.booking.doctor"
  | "hospitaladmin.doctors.schedule.appointments.booking.patient-result"
  | "hospitaladmin.doctors.schedule.appointments.booking.patient-search"
  | "hospitaladmin.doctors.schedule.appointments.booking.slot"
  | "hospitaladmin.doctors.schedule.appointments.create"
  | "hospitaladmin.doctors.schedule.appointments.search"
  | "hospitaladmin.doctors.schedule.full-week"
  | "hospitaladmin.doctors.schedule.inventory.create"
  | "hospitaladmin.doctors.schedule.inventory.search"
  | "hospitaladmin.doctors.schedule.ipd.admit"
  | "hospitaladmin.doctors.schedule.ipd.search"
  | "hospitaladmin.doctors.schedule.patients.appointment.complete"
  | "hospitaladmin.doctors.schedule.patients.create"
  | "hospitaladmin.doctors.schedule.patients.form.gender"
  | "hospitaladmin.doctors.schedule.patients.form.name"
  | "hospitaladmin.doctors.schedule.patients.form.phone"
  | "hospitaladmin.doctors.schedule.patients.form.submit"
  | "hospitaladmin.doctors.schedule.patients.search"
  | "hospitaladmin.doctors.schedule.patients.view"
  | "hospitaladmin.doctors.schedule.save"
  | "hospitaladmin.doctors.search"
  | "hospitaladmin.finance"
  | "hospitaladmin.finance.expense.submit"
  | "hospitaladmin.finance.loading"
  | "hospitaladmin.finance.revenue.submit"
  | "hospitaladmin.inventory.add-page"
  | "hospitaladmin.inventory.create"
  | "hospitaladmin.inventory.search"
  | "hospitaladmin.ipd.admit"
  | "hospitaladmin.ipd.search"
  | "hospitaladmin.lab.appointments.booking.confirm"
  | "hospitaladmin.lab.appointments.booking.date"
  | "hospitaladmin.lab.appointments.booking.doctor"
  | "hospitaladmin.lab.appointments.booking.patient-result"
  | "hospitaladmin.lab.appointments.booking.patient-search"
  | "hospitaladmin.lab.appointments.booking.slot"
  | "hospitaladmin.lab.appointments.create"
  | "hospitaladmin.lab.appointments.search"
  | "hospitaladmin.lab.inventory.create"
  | "hospitaladmin.lab.inventory.search"
  | "hospitaladmin.lab.ipd.admit"
  | "hospitaladmin.lab.ipd.search"
  | "hospitaladmin.lab.patients.appointment.complete"
  | "hospitaladmin.lab.patients.create"
  | "hospitaladmin.lab.patients.form.gender"
  | "hospitaladmin.lab.patients.form.name"
  | "hospitaladmin.lab.patients.form.phone"
  | "hospitaladmin.lab.patients.form.submit"
  | "hospitaladmin.lab.patients.search"
  | "hospitaladmin.lab.patients.view"
  | "hospitaladmin.logout"
  | "hospitaladmin.nav.appointments"
  | "hospitaladmin.nav.billing"
  | "hospitaladmin.nav.configure"
  | "hospitaladmin.nav.consultation"
  | "hospitaladmin.nav.departments"
  | "hospitaladmin.nav.doctors"
  | "hospitaladmin.nav.finance"
  | "hospitaladmin.nav.inventory"
  | "hospitaladmin.nav.ipd"
  | "hospitaladmin.nav.overview"
  | "hospitaladmin.nav.patients"
  | "hospitaladmin.nav.reports"
  | "hospitaladmin.nav.staff"
  | "hospitaladmin.nav.subdepartments"
  | "hospitaladmin.nav.subdepartments.menu"
  | "hospitaladmin.nav.subdept-item"
  | "hospitaladmin.pathology.appointments.booking.confirm"
  | "hospitaladmin.pathology.appointments.booking.date"
  | "hospitaladmin.pathology.appointments.booking.doctor"
  | "hospitaladmin.pathology.appointments.booking.patient-result"
  | "hospitaladmin.pathology.appointments.booking.patient-search"
  | "hospitaladmin.pathology.appointments.booking.slot"
  | "hospitaladmin.pathology.appointments.create"
  | "hospitaladmin.pathology.appointments.search"
  | "hospitaladmin.pathology.inventory.create"
  | "hospitaladmin.pathology.inventory.search"
  | "hospitaladmin.pathology.ipd.admit"
  | "hospitaladmin.pathology.ipd.search"
  | "hospitaladmin.pathology.patients.appointment.complete"
  | "hospitaladmin.pathology.patients.create"
  | "hospitaladmin.pathology.patients.form.gender"
  | "hospitaladmin.pathology.patients.form.name"
  | "hospitaladmin.pathology.patients.form.phone"
  | "hospitaladmin.pathology.patients.form.submit"
  | "hospitaladmin.pathology.patients.search"
  | "hospitaladmin.pathology.patients.view"
  | "hospitaladmin.patients.appointment.complete"
  | "hospitaladmin.patients.create"
  | "hospitaladmin.patients.details.appointments"
  | "hospitaladmin.patients.form.gender"
  | "hospitaladmin.patients.form.name"
  | "hospitaladmin.patients.form.phone"
  | "hospitaladmin.patients.form.submit"
  | "hospitaladmin.patients.search"
  | "hospitaladmin.patients.view"
  | "hospitaladmin.pharmacy.appointments.booking.confirm"
  | "hospitaladmin.pharmacy.appointments.booking.date"
  | "hospitaladmin.pharmacy.appointments.booking.doctor"
  | "hospitaladmin.pharmacy.appointments.booking.patient-result"
  | "hospitaladmin.pharmacy.appointments.booking.patient-search"
  | "hospitaladmin.pharmacy.appointments.booking.slot"
  | "hospitaladmin.pharmacy.appointments.create"
  | "hospitaladmin.pharmacy.appointments.search"
  | "hospitaladmin.pharmacy.inventory.create"
  | "hospitaladmin.pharmacy.inventory.search"
  | "hospitaladmin.pharmacy.ipd.admit"
  | "hospitaladmin.pharmacy.ipd.search"
  | "hospitaladmin.pharmacy.patients.appointment.complete"
  | "hospitaladmin.pharmacy.patients.create"
  | "hospitaladmin.pharmacy.patients.form.gender"
  | "hospitaladmin.pharmacy.patients.form.name"
  | "hospitaladmin.pharmacy.patients.form.phone"
  | "hospitaladmin.pharmacy.patients.form.submit"
  | "hospitaladmin.pharmacy.patients.search"
  | "hospitaladmin.pharmacy.patients.view"
  | "hospitaladmin.profile"
  | "hospitaladmin.profile.change-password.submit"
  | "hospitaladmin.profile.confirm-password"
  | "hospitaladmin.profile.current-password"
  | "hospitaladmin.profile.email"
  | "hospitaladmin.profile.loading"
  | "hospitaladmin.profile.name"
  | "hospitaladmin.profile.new-password"
  | "hospitaladmin.profile.save"
  | "hospitaladmin.reports"
  | "hospitaladmin.reports.active-doctors"
  | "hospitaladmin.reports.completed-appointments"
  | "hospitaladmin.reports.total-appointments"
  | "hospitaladmin.reports.total-patients"
  | "hospitaladmin.reschedule.close-button"
  | "hospitaladmin.reschedule.confirm-button"
  | "hospitaladmin.reschedule.date-input"
  | "hospitaladmin.reschedule.department-select"
  | "hospitaladmin.reschedule.doctor-select"
  | "hospitaladmin.reschedule.modal"
  | "hospitaladmin.reschedule.slot-button"
  | "hospitaladmin.sidebar-nav"
  | "hospitaladmin.staff"
  | "hospitaladmin.staff.create"
  | "hospitaladmin.staff.loading"
  | "hospitaladmin.staff.save"
  | "hospitaladmin.staff.search"
  | "hospitaladmin.subdept"
  | "hospitaladmin.subdept-dashboard"
  | "parentdept.appointments.booking.confirm"
  | "parentdept.appointments.booking.date"
  | "parentdept.appointments.booking.doctor"
  | "parentdept.appointments.booking.patient-result"
  | "parentdept.appointments.booking.patient-search"
  | "parentdept.appointments.booking.slot"
  | "parentdept.appointments.create"
  | "parentdept.appointments.search"
  | "parentdept.dashboard"
  | "parentdept.dashboard.loading"
  | "parentdept.dashboard.tab.completed"
  | "parentdept.dashboard.tab.overview"
  | "parentdept.dashboard.tab.procedures"
  | "parentdept.dashboard.tab.queue"
  | "parentdept.dashboard.tab.records"
  | "parentdept.inventory.create"
  | "parentdept.inventory.search"
  | "parentdept.ipd.admit"
  | "parentdept.ipd.search"
  | "parentdept.logout"
  | "parentdept.nav.analytics"
  | "parentdept.nav.billing"
  | "parentdept.nav.inventory"
  | "parentdept.nav.overview"
  | "parentdept.nav.purchases"
  | "parentdept.nav.queue"
  | "parentdept.nav.reports"
  | "parentdept.nav.subdepts"
  | "parentdept.patients.appointment.complete"
  | "parentdept.patients.create"
  | "parentdept.patients.form.gender"
  | "parentdept.patients.form.name"
  | "parentdept.patients.form.phone"
  | "parentdept.patients.form.submit"
  | "parentdept.patients.search"
  | "parentdept.patients.view"
  | "public.appointment.provider"
  | "public.blog.panel"
  | "public.booking.date"
  | "public.booking.department"
  | "public.booking.doctor"
  | "public.booking.email"
  | "public.booking.name"
  | "public.booking.phone"
  | "public.booking.submit"
  | "public.brand.wordmark"
  | "public.cookie-policy"
  | "public.footer"
  | "public.footer.link.about"
  | "public.footer.link.blog"
  | "public.footer.link.contact"
  | "public.footer.link.cookies"
  | "public.footer.link.home"
  | "public.footer.link.logo"
  | "public.footer.link.privacy"
  | "public.footer.link.terms"
  | "public.footer.link.treatments"
  | "public.not-found"
  | "public.privacy-policy"
  | "public.terms-of-service"
  | "receptionist.appointments.create"
  | "receptionist.dashboard"
  | "receptionist.dashboard.loading"
  | "receptionist.logout"
  | "receptionist.nav.book"
  | "receptionist.nav.patients"
  | "receptionist.nav.queue"
  | "shared.account.dept.description"
  | "shared.account.dept.email"
  | "shared.account.dept.hod-name"
  | "shared.account.dept.name"
  | "shared.account.dept.phone"
  | "shared.account.dept.save"
  | "shared.account.email"
  | "shared.account.name"
  | "shared.account.panel"
  | "shared.account.password.confirm"
  | "shared.account.password.current"
  | "shared.account.password.new"
  | "shared.account.password.submit"
  | "shared.account.save"
  | "shared.appointments.booking.confirm"
  | "shared.appointments.booking.date"
  | "shared.appointments.booking.doctor"
  | "shared.appointments.booking.patient-result"
  | "shared.appointments.booking.patient-search"
  | "shared.appointments.booking.slot"
  | "shared.appointments.create"
  | "shared.appointments.search"
  | "shared.dynamic-dashboard"
  | "shared.leave-modal"
  | "shared.patients.appointment.complete"
  | "shared.patients.form.gender"
  | "shared.patients.form.name"
  | "shared.patients.form.phone"
  | "shared.patients.form.submit"
  | "shared.patients.search"
  | "shared.patients.view"
  | "staff.appointments.booking.confirm"
  | "staff.appointments.booking.date"
  | "staff.appointments.booking.doctor"
  | "staff.appointments.booking.patient-result"
  | "staff.appointments.booking.patient-search"
  | "staff.appointments.booking.slot"
  | "staff.appointments.create"
  | "staff.appointments.search"
  | "staff.dashboard"
  | "staff.dashboard.loading"
  | "staff.inventory.create"
  | "staff.inventory.search"
  | "staff.ipd.admit"
  | "staff.ipd.search"
  | "staff.logout"
  | "staff.nav.appointments"
  | "staff.nav.billing"
  | "staff.nav.bills"
  | "staff.nav.followups"
  | "staff.nav.overview"
  | "staff.nav.patients"
  | "staff.nav.queue"
  | "staff.patients.appointment.complete"
  | "staff.patients.create"
  | "staff.patients.form.gender"
  | "staff.patients.form.name"
  | "staff.patients.form.phone"
  | "staff.patients.form.submit"
  | "staff.patients.search"
  | "staff.patients.view"
  | "staff.profile"
  | "subdept.billing-dept.appointments.booking.confirm"
  | "subdept.billing-dept.appointments.booking.date"
  | "subdept.billing-dept.appointments.booking.doctor"
  | "subdept.billing-dept.appointments.booking.patient-result"
  | "subdept.billing-dept.appointments.booking.patient-search"
  | "subdept.billing-dept.appointments.booking.slot"
  | "subdept.billing-dept.appointments.create"
  | "subdept.billing-dept.appointments.search"
  | "subdept.billing-dept.billing-queue"
  | "subdept.billing-dept.inventory.create"
  | "subdept.billing-dept.inventory.search"
  | "subdept.billing-dept.ipd.admit"
  | "subdept.billing-dept.ipd.search"
  | "subdept.billing-dept.open-queue"
  | "subdept.billing-dept.patients.appointment.complete"
  | "subdept.billing-dept.patients.create"
  | "subdept.billing-dept.patients.form.gender"
  | "subdept.billing-dept.patients.form.name"
  | "subdept.billing-dept.patients.form.phone"
  | "subdept.billing-dept.patients.form.submit"
  | "subdept.billing-dept.patients.search"
  | "subdept.billing-dept.patients.view"
  | "subdept.billing-dept.view-finance"
  | "subdept.critical-care.admit"
  | "subdept.critical-care.discharge"
  | "subdept.critical-care.refresh"
  | "subdept.dashboard"
  | "subdept.dashboard.loading"
  | "subdept.hr.manage-doctors"
  | "subdept.hr.manage-staff"
  | "subdept.hr.manage-staff-doctors"
  | "subdept.hr.open-doctors"
  | "subdept.hr.open-staff"
  | "subdept.hr.refresh-stats"
  | "subdept.modal.edit-record.cancel"
  | "subdept.modal.edit-record.submit"
  | "subdept.modal.transfer-patient.cancel"
  | "subdept.modal.transfer-patient.submit"
  | "subdept.modal.view-prescription.download"
  | "subdept.pathology.appointments.booking.confirm"
  | "subdept.pathology.appointments.booking.date"
  | "subdept.pathology.appointments.booking.doctor"
  | "subdept.pathology.appointments.booking.patient-result"
  | "subdept.pathology.appointments.booking.patient-search"
  | "subdept.pathology.appointments.booking.slot"
  | "subdept.pathology.appointments.create"
  | "subdept.pathology.appointments.search"
  | "subdept.pathology.inventory.create"
  | "subdept.pathology.inventory.search"
  | "subdept.pathology.ipd.admit"
  | "subdept.pathology.ipd.search"
  | "subdept.pathology.patients.appointment.complete"
  | "subdept.pathology.patients.create"
  | "subdept.pathology.patients.form.gender"
  | "subdept.pathology.patients.form.name"
  | "subdept.pathology.patients.form.phone"
  | "subdept.pathology.patients.form.submit"
  | "subdept.pathology.patients.search"
  | "subdept.pathology.patients.view"
  | "subdept.patients.appointments.booking.confirm"
  | "subdept.patients.appointments.booking.date"
  | "subdept.patients.appointments.booking.doctor"
  | "subdept.patients.appointments.booking.patient-result"
  | "subdept.patients.appointments.booking.patient-search"
  | "subdept.patients.appointments.booking.slot"
  | "subdept.patients.appointments.create"
  | "subdept.patients.appointments.search"
  | "subdept.patients.inventory.create"
  | "subdept.patients.inventory.search"
  | "subdept.patients.ipd.admit"
  | "subdept.patients.ipd.search"
  | "subdept.patients.patients.appointment.complete"
  | "subdept.patients.patients.create"
  | "subdept.patients.patients.form.gender"
  | "subdept.patients.patients.form.name"
  | "subdept.patients.patients.form.phone"
  | "subdept.patients.patients.form.submit"
  | "subdept.patients.patients.search"
  | "subdept.patients.patients.view"
  | "subdept.pharmacy.appointments.booking.confirm"
  | "subdept.pharmacy.appointments.booking.date"
  | "subdept.pharmacy.appointments.booking.doctor"
  | "subdept.pharmacy.appointments.booking.patient-result"
  | "subdept.pharmacy.appointments.booking.patient-search"
  | "subdept.pharmacy.appointments.booking.slot"
  | "subdept.pharmacy.appointments.create"
  | "subdept.pharmacy.appointments.search"
  | "subdept.pharmacy.counter-sale.modal"
  | "subdept.pharmacy.finance.panel"
  | "subdept.pharmacy.inventory.create"
  | "subdept.pharmacy.inventory.panel"
  | "subdept.pharmacy.inventory.search"
  | "subdept.pharmacy.ipd.admit"
  | "subdept.pharmacy.ipd.search"
  | "subdept.pharmacy.patients.appointment.complete"
  | "subdept.pharmacy.patients.create"
  | "subdept.pharmacy.patients.form.gender"
  | "subdept.pharmacy.patients.form.name"
  | "subdept.pharmacy.patients.form.phone"
  | "subdept.pharmacy.patients.form.submit"
  | "subdept.pharmacy.patients.search"
  | "subdept.pharmacy.patients.view"
  | "subdept.procedures.panel"
  | "subdept.profile"
  | "subdept.shell.logout"
  | "subdept.shell.nav.account-settings"
  | "subdept.shell.nav.analytics"
  | "subdept.shell.nav.appointments"
  | "subdept.shell.nav.billing"
  | "subdept.shell.nav.billing-queue"
  | "subdept.shell.nav.consultations"
  | "subdept.shell.nav.counter-sell"
  | "subdept.shell.nav.doctors"
  | "subdept.shell.nav.expense"
  | "subdept.shell.nav.expenses"
  | "subdept.shell.nav.finance"
  | "subdept.shell.nav.inventory"
  | "subdept.shell.nav.orders"
  | "subdept.shell.nav.overview"
  | "subdept.shell.nav.panels"
  | "subdept.shell.nav.patients"
  | "subdept.shell.nav.procedures"
  | "subdept.shell.nav.purchases"
  | "subdept.shell.nav.queue"
  | "subdept.shell.nav.records"
  | "subdept.shell.nav.reports"
  | "subdept.shell.nav.results"
  | "subdept.shell.nav.revenue"
  | "subdept.shell.nav.samples"
  | "subdept.shell.nav.staff"
  | "subdept.shell.nav.tests"
  | "subdept.specialty.complete"
  | "subdept.specialty.refresh"
  | "subdept.specialty.refresh-records"
  | "subdept.specialty.start"
  | "superadmin.dashboard"
  | "superadmin.dashboard.loading"
  | "superadmin.hospitals.create.admin-name"
  | "superadmin.hospitals.create.confirm-password"
  | "superadmin.hospitals.create.email"
  | "superadmin.hospitals.create.error"
  | "superadmin.hospitals.create.mobile"
  | "superadmin.hospitals.create.name"
  | "superadmin.hospitals.create.open"
  | "superadmin.hospitals.create.password"
  | "superadmin.hospitals.create.submit"
  | "superadmin.hospitals.create.success"
  | "superadmin.logout"
  | "superadmin.nav.activity"
  | "superadmin.nav.hospitals"
  | "superadmin.nav.overview"
  | "superadmin.nav.settings"
  | "support.ambulance.dashboard"
  | "support.dashboard"
  | "support.housekeeping.dashboard"
  | "support.logout"
  | "support.nav.appointments"
  | "support.nav.dept-info"
  | "support.nav.overview"
  | "support.nav.patients"
  | "support.nav.queue"
  | "support.nav.subdepts";

export const UI_ANCHOR_IDS = [
  "administrative.dashboard",
  "administrative.logout",
  "administrative.nav.appointments",
  "administrative.nav.dept-info",
  "administrative.nav.overview",
  "administrative.nav.patients",
  "administrative.nav.queue",
  "administrative.nav.subdepts",
  "auth.change-password.confirm",
  "auth.change-password.current",
  "auth.change-password.new",
  "auth.change-password.submit",
  "auth.finance.login.email",
  "auth.finance.login.password",
  "auth.finance.login.submit",
  "auth.forgot.close",
  "auth.forgot.confirm",
  "auth.forgot.email",
  "auth.forgot.go-to-signin",
  "auth.forgot.otp-1",
  "auth.forgot.otp-2",
  "auth.forgot.otp-3",
  "auth.forgot.otp-4",
  "auth.forgot.otp-5",
  "auth.forgot.otp-6",
  "auth.forgot.password",
  "auth.forgot.resend-otp",
  "auth.forgot.send-otp",
  "auth.forgot.submit",
  "auth.forgot.verify-otp",
  "auth.login.email",
  "auth.login.password",
  "auth.login.submit",
  "auth.parentdept.login.email",
  "auth.parentdept.login.password",
  "auth.parentdept.login.submit",
  "auth.signup.admin-name",
  "auth.signup.back",
  "auth.signup.confirm-password",
  "auth.signup.email",
  "auth.signup.hospital-name",
  "auth.signup.mobile",
  "auth.signup.otp-1",
  "auth.signup.otp-2",
  "auth.signup.otp-3",
  "auth.signup.otp-4",
  "auth.signup.otp-5",
  "auth.signup.otp-6",
  "auth.signup.password",
  "auth.signup.resend-otp",
  "auth.signup.submit",
  "auth.signup.verify",
  "auth.staff.login.email",
  "auth.staff.login.password",
  "auth.staff.login.submit",
  "auth.subdept.login.email",
  "auth.subdept.login.password",
  "auth.subdept.login.submit",
  "auth.superadmin.login.email",
  "auth.superadmin.login.password",
  "auth.superadmin.login.security-key",
  "auth.superadmin.login.submit",
  "clinical.dashboard",
  "clinical.dashboard.loading",
  "clinical.dental.dashboard",
  "clinical.followup.dashboard",
  "clinical.logout",
  "clinical.nav.appointments",
  "clinical.nav.dept-info",
  "clinical.nav.overview",
  "clinical.nav.patients",
  "clinical.nav.queue",
  "clinical.nav.subdepts",
  "clinical.nursing.dashboard",
  "clinical.opd.dashboard",
  "diagnostic.dashboard",
  "diagnostic.lab.dashboard",
  "diagnostic.logout",
  "diagnostic.nav.appointments",
  "diagnostic.nav.dept-info",
  "diagnostic.nav.overview",
  "diagnostic.nav.patients",
  "diagnostic.nav.queue",
  "diagnostic.nav.subdepts",
  "doctor.appointments.booking.confirm",
  "doctor.appointments.booking.date",
  "doctor.appointments.booking.doctor",
  "doctor.appointments.booking.patient-result",
  "doctor.appointments.booking.patient-search",
  "doctor.appointments.booking.slot",
  "doctor.appointments.create",
  "doctor.appointments.search",
  "doctor.attendance.checkout",
  "doctor.availability.modal",
  "doctor.dashboard",
  "doctor.dashboard.loading",
  "doctor.inventory.create",
  "doctor.inventory.search",
  "doctor.ipd.admit",
  "doctor.ipd.search",
  "doctor.logout",
  "doctor.nav.appointments",
  "doctor.nav.attendance",
  "doctor.nav.patients",
  "doctor.nav.prescription-settings",
  "doctor.nav.profile",
  "doctor.nav.reports",
  "doctor.nav.rx",
  "doctor.nav.schedule",
  "doctor.nav.schedule-mgmt",
  "doctor.nav.treatment-plans",
  "doctor.patient-profile.panel",
  "doctor.patients.appointment.complete",
  "doctor.patients.create",
  "doctor.patients.form.gender",
  "doctor.patients.form.name",
  "doctor.patients.form.phone",
  "doctor.patients.form.submit",
  "doctor.patients.search",
  "doctor.patients.view",
  "doctor.prescription-settings.panel",
  "doctor.profile",
  "doctor.profile.panel",
  "doctor.profile.save",
  "doctor.rx.add-medication",
  "doctor.rx.management-panel",
  "doctor.rx.prescription-page",
  "doctor.rx.save",
  "doctor.rx.voice.close",
  "doctor.rx.voice.recorder",
  "doctor.rx.voice.start",
  "doctor.schedule.consult",
  "doctor.schedule.edit-rx",
  "doctor.schedule.full-week",
  "doctor.schedule.modal",
  "doctor.schedule.save",
  "doctor.schedule.view-rx",
  "doctor.treatment-plan.panel",
  "finance.bills.create",
  "finance.bills.create-alt",
  "finance.bills.create-list",
  "finance.bills.submit",
  "finance.dashboard",
  "finance.dashboard.loading",
  "finance.dept.panel",
  "finance.expenses.create",
  "finance.expenses.create-list",
  "finance.expenses.submit",
  "finance.logout",
  "finance.nav.bills",
  "finance.nav.expenses",
  "finance.nav.overview",
  "finance.nav.payments",
  "finance.nav.reports",
  "finance.payments.initiate",
  "finance.payments.initiate-modal",
  "finance.payments.submit",
  "hospitaladmin.appointments",
  "hospitaladmin.appointments.booking.confirm",
  "hospitaladmin.appointments.booking.date",
  "hospitaladmin.appointments.booking.doctor",
  "hospitaladmin.appointments.booking.patient-result",
  "hospitaladmin.appointments.booking.patient-search",
  "hospitaladmin.appointments.booking.slot",
  "hospitaladmin.appointments.create",
  "hospitaladmin.appointments.modal",
  "hospitaladmin.appointments.search",
  "hospitaladmin.billing",
  "hospitaladmin.configure",
  "hospitaladmin.configure.departments.create",
  "hospitaladmin.configure.departments.panel",
  "hospitaladmin.configure.departments.save",
  "hospitaladmin.configure.departments.search",
  "hospitaladmin.configure.loading",
  "hospitaladmin.configure.services.create",
  "hospitaladmin.configure.services.save",
  "hospitaladmin.configure.subdepartments.create",
  "hospitaladmin.configure.subdepartments.save",
  "hospitaladmin.configure.subdepartments.search",
  "hospitaladmin.configure.tab.appointments",
  "hospitaladmin.configure.tab.billing",
  "hospitaladmin.configure.tab.departments",
  "hospitaladmin.configure.tab.doctors",
  "hospitaladmin.configure.tab.finance",
  "hospitaladmin.configure.tab.inventory",
  "hospitaladmin.configure.tab.overview",
  "hospitaladmin.configure.tab.patients",
  "hospitaladmin.configure.tab.permissions",
  "hospitaladmin.configure.tab.services",
  "hospitaladmin.configure.tab.settings",
  "hospitaladmin.configure.tab.staff",
  "hospitaladmin.configure.tab.subdepts",
  "hospitaladmin.configure.tab.treatments",
  "hospitaladmin.configure.tab.wards",
  "hospitaladmin.configure.wards.create",
  "hospitaladmin.configure.wards.save",
  "hospitaladmin.consultation",
  "hospitaladmin.consultation.prescription-page",
  "hospitaladmin.consultation.start",
  "hospitaladmin.consultation.status",
  "hospitaladmin.dashboard",
  "hospitaladmin.dashboard.loading",
  "hospitaladmin.dashboard.tab.appointments",
  "hospitaladmin.dashboard.tab.billing",
  "hospitaladmin.dashboard.tab.departments",
  "hospitaladmin.dashboard.tab.inventory",
  "hospitaladmin.dashboard.tab.ipd",
  "hospitaladmin.dashboard.tab.overview",
  "hospitaladmin.dashboard.tab.patients",
  "hospitaladmin.dashboard.tab.reports",
  "hospitaladmin.dashboard.tab.staff",
  "hospitaladmin.doctors",
  "hospitaladmin.doctors.create",
  "hospitaladmin.doctors.form.consultation-fee",
  "hospitaladmin.doctors.form.email",
  "hospitaladmin.doctors.form.name",
  "hospitaladmin.doctors.form.phone",
  "hospitaladmin.doctors.form.specialization",
  "hospitaladmin.doctors.loading",
  "hospitaladmin.doctors.save",
  "hospitaladmin.doctors.schedule",
  "hospitaladmin.doctors.schedule.appointments.booking.confirm",
  "hospitaladmin.doctors.schedule.appointments.booking.date",
  "hospitaladmin.doctors.schedule.appointments.booking.doctor",
  "hospitaladmin.doctors.schedule.appointments.booking.patient-result",
  "hospitaladmin.doctors.schedule.appointments.booking.patient-search",
  "hospitaladmin.doctors.schedule.appointments.booking.slot",
  "hospitaladmin.doctors.schedule.appointments.create",
  "hospitaladmin.doctors.schedule.appointments.search",
  "hospitaladmin.doctors.schedule.full-week",
  "hospitaladmin.doctors.schedule.inventory.create",
  "hospitaladmin.doctors.schedule.inventory.search",
  "hospitaladmin.doctors.schedule.ipd.admit",
  "hospitaladmin.doctors.schedule.ipd.search",
  "hospitaladmin.doctors.schedule.patients.appointment.complete",
  "hospitaladmin.doctors.schedule.patients.create",
  "hospitaladmin.doctors.schedule.patients.form.gender",
  "hospitaladmin.doctors.schedule.patients.form.name",
  "hospitaladmin.doctors.schedule.patients.form.phone",
  "hospitaladmin.doctors.schedule.patients.form.submit",
  "hospitaladmin.doctors.schedule.patients.search",
  "hospitaladmin.doctors.schedule.patients.view",
  "hospitaladmin.doctors.schedule.save",
  "hospitaladmin.doctors.search",
  "hospitaladmin.finance",
  "hospitaladmin.finance.expense.submit",
  "hospitaladmin.finance.loading",
  "hospitaladmin.finance.revenue.submit",
  "hospitaladmin.inventory.add-page",
  "hospitaladmin.inventory.create",
  "hospitaladmin.inventory.search",
  "hospitaladmin.ipd.admit",
  "hospitaladmin.ipd.search",
  "hospitaladmin.lab.appointments.booking.confirm",
  "hospitaladmin.lab.appointments.booking.date",
  "hospitaladmin.lab.appointments.booking.doctor",
  "hospitaladmin.lab.appointments.booking.patient-result",
  "hospitaladmin.lab.appointments.booking.patient-search",
  "hospitaladmin.lab.appointments.booking.slot",
  "hospitaladmin.lab.appointments.create",
  "hospitaladmin.lab.appointments.search",
  "hospitaladmin.lab.inventory.create",
  "hospitaladmin.lab.inventory.search",
  "hospitaladmin.lab.ipd.admit",
  "hospitaladmin.lab.ipd.search",
  "hospitaladmin.lab.patients.appointment.complete",
  "hospitaladmin.lab.patients.create",
  "hospitaladmin.lab.patients.form.gender",
  "hospitaladmin.lab.patients.form.name",
  "hospitaladmin.lab.patients.form.phone",
  "hospitaladmin.lab.patients.form.submit",
  "hospitaladmin.lab.patients.search",
  "hospitaladmin.lab.patients.view",
  "hospitaladmin.logout",
  "hospitaladmin.nav.appointments",
  "hospitaladmin.nav.billing",
  "hospitaladmin.nav.configure",
  "hospitaladmin.nav.consultation",
  "hospitaladmin.nav.departments",
  "hospitaladmin.nav.doctors",
  "hospitaladmin.nav.finance",
  "hospitaladmin.nav.inventory",
  "hospitaladmin.nav.ipd",
  "hospitaladmin.nav.overview",
  "hospitaladmin.nav.patients",
  "hospitaladmin.nav.reports",
  "hospitaladmin.nav.staff",
  "hospitaladmin.nav.subdepartments",
  "hospitaladmin.nav.subdepartments.menu",
  "hospitaladmin.nav.subdept-item",
  "hospitaladmin.pathology.appointments.booking.confirm",
  "hospitaladmin.pathology.appointments.booking.date",
  "hospitaladmin.pathology.appointments.booking.doctor",
  "hospitaladmin.pathology.appointments.booking.patient-result",
  "hospitaladmin.pathology.appointments.booking.patient-search",
  "hospitaladmin.pathology.appointments.booking.slot",
  "hospitaladmin.pathology.appointments.create",
  "hospitaladmin.pathology.appointments.search",
  "hospitaladmin.pathology.inventory.create",
  "hospitaladmin.pathology.inventory.search",
  "hospitaladmin.pathology.ipd.admit",
  "hospitaladmin.pathology.ipd.search",
  "hospitaladmin.pathology.patients.appointment.complete",
  "hospitaladmin.pathology.patients.create",
  "hospitaladmin.pathology.patients.form.gender",
  "hospitaladmin.pathology.patients.form.name",
  "hospitaladmin.pathology.patients.form.phone",
  "hospitaladmin.pathology.patients.form.submit",
  "hospitaladmin.pathology.patients.search",
  "hospitaladmin.pathology.patients.view",
  "hospitaladmin.patients.appointment.complete",
  "hospitaladmin.patients.create",
  "hospitaladmin.patients.details.appointments",
  "hospitaladmin.patients.form.gender",
  "hospitaladmin.patients.form.name",
  "hospitaladmin.patients.form.phone",
  "hospitaladmin.patients.form.submit",
  "hospitaladmin.patients.search",
  "hospitaladmin.patients.view",
  "hospitaladmin.pharmacy.appointments.booking.confirm",
  "hospitaladmin.pharmacy.appointments.booking.date",
  "hospitaladmin.pharmacy.appointments.booking.doctor",
  "hospitaladmin.pharmacy.appointments.booking.patient-result",
  "hospitaladmin.pharmacy.appointments.booking.patient-search",
  "hospitaladmin.pharmacy.appointments.booking.slot",
  "hospitaladmin.pharmacy.appointments.create",
  "hospitaladmin.pharmacy.appointments.search",
  "hospitaladmin.pharmacy.inventory.create",
  "hospitaladmin.pharmacy.inventory.search",
  "hospitaladmin.pharmacy.ipd.admit",
  "hospitaladmin.pharmacy.ipd.search",
  "hospitaladmin.pharmacy.patients.appointment.complete",
  "hospitaladmin.pharmacy.patients.create",
  "hospitaladmin.pharmacy.patients.form.gender",
  "hospitaladmin.pharmacy.patients.form.name",
  "hospitaladmin.pharmacy.patients.form.phone",
  "hospitaladmin.pharmacy.patients.form.submit",
  "hospitaladmin.pharmacy.patients.search",
  "hospitaladmin.pharmacy.patients.view",
  "hospitaladmin.profile",
  "hospitaladmin.profile.change-password.submit",
  "hospitaladmin.profile.confirm-password",
  "hospitaladmin.profile.current-password",
  "hospitaladmin.profile.email",
  "hospitaladmin.profile.loading",
  "hospitaladmin.profile.name",
  "hospitaladmin.profile.new-password",
  "hospitaladmin.profile.save",
  "hospitaladmin.reports",
  "hospitaladmin.reports.active-doctors",
  "hospitaladmin.reports.completed-appointments",
  "hospitaladmin.reports.total-appointments",
  "hospitaladmin.reports.total-patients",
  "hospitaladmin.reschedule.close-button",
  "hospitaladmin.reschedule.confirm-button",
  "hospitaladmin.reschedule.date-input",
  "hospitaladmin.reschedule.department-select",
  "hospitaladmin.reschedule.doctor-select",
  "hospitaladmin.reschedule.modal",
  "hospitaladmin.reschedule.slot-button",
  "hospitaladmin.sidebar-nav",
  "hospitaladmin.staff",
  "hospitaladmin.staff.create",
  "hospitaladmin.staff.loading",
  "hospitaladmin.staff.save",
  "hospitaladmin.staff.search",
  "hospitaladmin.subdept",
  "hospitaladmin.subdept-dashboard",
  "parentdept.appointments.booking.confirm",
  "parentdept.appointments.booking.date",
  "parentdept.appointments.booking.doctor",
  "parentdept.appointments.booking.patient-result",
  "parentdept.appointments.booking.patient-search",
  "parentdept.appointments.booking.slot",
  "parentdept.appointments.create",
  "parentdept.appointments.search",
  "parentdept.dashboard",
  "parentdept.dashboard.loading",
  "parentdept.dashboard.tab.completed",
  "parentdept.dashboard.tab.overview",
  "parentdept.dashboard.tab.procedures",
  "parentdept.dashboard.tab.queue",
  "parentdept.dashboard.tab.records",
  "parentdept.inventory.create",
  "parentdept.inventory.search",
  "parentdept.ipd.admit",
  "parentdept.ipd.search",
  "parentdept.logout",
  "parentdept.nav.analytics",
  "parentdept.nav.billing",
  "parentdept.nav.inventory",
  "parentdept.nav.overview",
  "parentdept.nav.purchases",
  "parentdept.nav.queue",
  "parentdept.nav.reports",
  "parentdept.nav.subdepts",
  "parentdept.patients.appointment.complete",
  "parentdept.patients.create",
  "parentdept.patients.form.gender",
  "parentdept.patients.form.name",
  "parentdept.patients.form.phone",
  "parentdept.patients.form.submit",
  "parentdept.patients.search",
  "parentdept.patients.view",
  "public.appointment.provider",
  "public.blog.panel",
  "public.booking.date",
  "public.booking.department",
  "public.booking.doctor",
  "public.booking.email",
  "public.booking.name",
  "public.booking.phone",
  "public.booking.submit",
  "public.brand.wordmark",
  "public.cookie-policy",
  "public.footer",
  "public.footer.link.about",
  "public.footer.link.blog",
  "public.footer.link.contact",
  "public.footer.link.cookies",
  "public.footer.link.home",
  "public.footer.link.logo",
  "public.footer.link.privacy",
  "public.footer.link.terms",
  "public.footer.link.treatments",
  "public.not-found",
  "public.privacy-policy",
  "public.terms-of-service",
  "receptionist.appointments.create",
  "receptionist.dashboard",
  "receptionist.dashboard.loading",
  "receptionist.logout",
  "receptionist.nav.book",
  "receptionist.nav.patients",
  "receptionist.nav.queue",
  "shared.account.dept.description",
  "shared.account.dept.email",
  "shared.account.dept.hod-name",
  "shared.account.dept.name",
  "shared.account.dept.phone",
  "shared.account.dept.save",
  "shared.account.email",
  "shared.account.name",
  "shared.account.panel",
  "shared.account.password.confirm",
  "shared.account.password.current",
  "shared.account.password.new",
  "shared.account.password.submit",
  "shared.account.save",
  "shared.appointments.booking.confirm",
  "shared.appointments.booking.date",
  "shared.appointments.booking.doctor",
  "shared.appointments.booking.patient-result",
  "shared.appointments.booking.patient-search",
  "shared.appointments.booking.slot",
  "shared.appointments.create",
  "shared.appointments.search",
  "shared.dynamic-dashboard",
  "shared.leave-modal",
  "shared.patients.appointment.complete",
  "shared.patients.form.gender",
  "shared.patients.form.name",
  "shared.patients.form.phone",
  "shared.patients.form.submit",
  "shared.patients.search",
  "shared.patients.view",
  "staff.appointments.booking.confirm",
  "staff.appointments.booking.date",
  "staff.appointments.booking.doctor",
  "staff.appointments.booking.patient-result",
  "staff.appointments.booking.patient-search",
  "staff.appointments.booking.slot",
  "staff.appointments.create",
  "staff.appointments.search",
  "staff.dashboard",
  "staff.dashboard.loading",
  "staff.inventory.create",
  "staff.inventory.search",
  "staff.ipd.admit",
  "staff.ipd.search",
  "staff.logout",
  "staff.nav.appointments",
  "staff.nav.billing",
  "staff.nav.bills",
  "staff.nav.followups",
  "staff.nav.overview",
  "staff.nav.patients",
  "staff.nav.queue",
  "staff.patients.appointment.complete",
  "staff.patients.create",
  "staff.patients.form.gender",
  "staff.patients.form.name",
  "staff.patients.form.phone",
  "staff.patients.form.submit",
  "staff.patients.search",
  "staff.patients.view",
  "staff.profile",
  "subdept.billing-dept.appointments.booking.confirm",
  "subdept.billing-dept.appointments.booking.date",
  "subdept.billing-dept.appointments.booking.doctor",
  "subdept.billing-dept.appointments.booking.patient-result",
  "subdept.billing-dept.appointments.booking.patient-search",
  "subdept.billing-dept.appointments.booking.slot",
  "subdept.billing-dept.appointments.create",
  "subdept.billing-dept.appointments.search",
  "subdept.billing-dept.billing-queue",
  "subdept.billing-dept.inventory.create",
  "subdept.billing-dept.inventory.search",
  "subdept.billing-dept.ipd.admit",
  "subdept.billing-dept.ipd.search",
  "subdept.billing-dept.open-queue",
  "subdept.billing-dept.patients.appointment.complete",
  "subdept.billing-dept.patients.create",
  "subdept.billing-dept.patients.form.gender",
  "subdept.billing-dept.patients.form.name",
  "subdept.billing-dept.patients.form.phone",
  "subdept.billing-dept.patients.form.submit",
  "subdept.billing-dept.patients.search",
  "subdept.billing-dept.patients.view",
  "subdept.billing-dept.view-finance",
  "subdept.critical-care.admit",
  "subdept.critical-care.discharge",
  "subdept.critical-care.refresh",
  "subdept.dashboard",
  "subdept.dashboard.loading",
  "subdept.hr.manage-doctors",
  "subdept.hr.manage-staff",
  "subdept.hr.manage-staff-doctors",
  "subdept.hr.open-doctors",
  "subdept.hr.open-staff",
  "subdept.hr.refresh-stats",
  "subdept.modal.edit-record.cancel",
  "subdept.modal.edit-record.submit",
  "subdept.modal.transfer-patient.cancel",
  "subdept.modal.transfer-patient.submit",
  "subdept.modal.view-prescription.download",
  "subdept.pathology.appointments.booking.confirm",
  "subdept.pathology.appointments.booking.date",
  "subdept.pathology.appointments.booking.doctor",
  "subdept.pathology.appointments.booking.patient-result",
  "subdept.pathology.appointments.booking.patient-search",
  "subdept.pathology.appointments.booking.slot",
  "subdept.pathology.appointments.create",
  "subdept.pathology.appointments.search",
  "subdept.pathology.inventory.create",
  "subdept.pathology.inventory.search",
  "subdept.pathology.ipd.admit",
  "subdept.pathology.ipd.search",
  "subdept.pathology.patients.appointment.complete",
  "subdept.pathology.patients.create",
  "subdept.pathology.patients.form.gender",
  "subdept.pathology.patients.form.name",
  "subdept.pathology.patients.form.phone",
  "subdept.pathology.patients.form.submit",
  "subdept.pathology.patients.search",
  "subdept.pathology.patients.view",
  "subdept.patients.appointments.booking.confirm",
  "subdept.patients.appointments.booking.date",
  "subdept.patients.appointments.booking.doctor",
  "subdept.patients.appointments.booking.patient-result",
  "subdept.patients.appointments.booking.patient-search",
  "subdept.patients.appointments.booking.slot",
  "subdept.patients.appointments.create",
  "subdept.patients.appointments.search",
  "subdept.patients.inventory.create",
  "subdept.patients.inventory.search",
  "subdept.patients.ipd.admit",
  "subdept.patients.ipd.search",
  "subdept.patients.patients.appointment.complete",
  "subdept.patients.patients.create",
  "subdept.patients.patients.form.gender",
  "subdept.patients.patients.form.name",
  "subdept.patients.patients.form.phone",
  "subdept.patients.patients.form.submit",
  "subdept.patients.patients.search",
  "subdept.patients.patients.view",
  "subdept.pharmacy.appointments.booking.confirm",
  "subdept.pharmacy.appointments.booking.date",
  "subdept.pharmacy.appointments.booking.doctor",
  "subdept.pharmacy.appointments.booking.patient-result",
  "subdept.pharmacy.appointments.booking.patient-search",
  "subdept.pharmacy.appointments.booking.slot",
  "subdept.pharmacy.appointments.create",
  "subdept.pharmacy.appointments.search",
  "subdept.pharmacy.counter-sale.modal",
  "subdept.pharmacy.finance.panel",
  "subdept.pharmacy.inventory.create",
  "subdept.pharmacy.inventory.panel",
  "subdept.pharmacy.inventory.search",
  "subdept.pharmacy.ipd.admit",
  "subdept.pharmacy.ipd.search",
  "subdept.pharmacy.patients.appointment.complete",
  "subdept.pharmacy.patients.create",
  "subdept.pharmacy.patients.form.gender",
  "subdept.pharmacy.patients.form.name",
  "subdept.pharmacy.patients.form.phone",
  "subdept.pharmacy.patients.form.submit",
  "subdept.pharmacy.patients.search",
  "subdept.pharmacy.patients.view",
  "subdept.procedures.panel",
  "subdept.profile",
  "subdept.shell.logout",
  "subdept.shell.nav.account-settings",
  "subdept.shell.nav.analytics",
  "subdept.shell.nav.appointments",
  "subdept.shell.nav.billing",
  "subdept.shell.nav.billing-queue",
  "subdept.shell.nav.consultations",
  "subdept.shell.nav.counter-sell",
  "subdept.shell.nav.doctors",
  "subdept.shell.nav.expense",
  "subdept.shell.nav.expenses",
  "subdept.shell.nav.finance",
  "subdept.shell.nav.inventory",
  "subdept.shell.nav.orders",
  "subdept.shell.nav.overview",
  "subdept.shell.nav.panels",
  "subdept.shell.nav.patients",
  "subdept.shell.nav.procedures",
  "subdept.shell.nav.purchases",
  "subdept.shell.nav.queue",
  "subdept.shell.nav.records",
  "subdept.shell.nav.reports",
  "subdept.shell.nav.results",
  "subdept.shell.nav.revenue",
  "subdept.shell.nav.samples",
  "subdept.shell.nav.staff",
  "subdept.shell.nav.tests",
  "subdept.specialty.complete",
  "subdept.specialty.refresh",
  "subdept.specialty.refresh-records",
  "subdept.specialty.start",
  "superadmin.dashboard",
  "superadmin.dashboard.loading",
  "superadmin.hospitals.create.admin-name",
  "superadmin.hospitals.create.confirm-password",
  "superadmin.hospitals.create.email",
  "superadmin.hospitals.create.error",
  "superadmin.hospitals.create.mobile",
  "superadmin.hospitals.create.name",
  "superadmin.hospitals.create.open",
  "superadmin.hospitals.create.password",
  "superadmin.hospitals.create.submit",
  "superadmin.hospitals.create.success",
  "superadmin.logout",
  "superadmin.nav.activity",
  "superadmin.nav.hospitals",
  "superadmin.nav.overview",
  "superadmin.nav.settings",
  "support.ambulance.dashboard",
  "support.dashboard",
  "support.housekeeping.dashboard",
  "support.logout",
  "support.nav.appointments",
  "support.nav.dept-info",
  "support.nav.overview",
  "support.nav.patients",
  "support.nav.queue",
  "support.nav.subdepts",
] as const satisfies readonly UIAnchorId[];
