global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: medinexplus-web
    metrics_path: /api/metrics
    static_configs:
      - targets: ["web:3000"]

  - job_name: mysqld-exporter
    static_configs:
      - targets: ["mysqld-exporter:9104"]

  - job_name: n8n-app
    metrics_path: /metrics
    scheme: https
    scrape_interval: 30s
    static_configs:
      - targets: ["n8n.ansarisaif.com"]
        labels:
          service: n8n
          environment: production
